### PR TITLE
use renamed elixir_uuid and update deps and credo

### PR DESCRIPTION
**Pull request by sitch**
`uuid` was renamed to `elixir_uuid` so I changed this dep name and fix two credo errors -- one for the ordering of assignment destructuring and one for moduledoc's missing.  All tests pass

### CODE REVIEW

**Comment by ayrat555** [comment]
@sitch thanks for the contribution!

**Comment by sitch** [comment]
@ayrat555 Thanks for the repo! :+1:

**Comment by ayrat555** [comment]
you can also check https://github.com/ayrat555/clope . It's also an algorithm for categorical attributes

**Comment by sitch** [comment]
nice thanks! I have an implementation for Silhouette clustering as well -- happy to put that somewhere if its useful

**Comment by ayrat555** [comment]
I think you can put to the readme in similar algorithms section

**Pull request merged**
